- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'
  sudo: yes
- name: Upgrade packages
  apt: update_cache=yes upgrade=yes
  sudo: yes

- name: Accept Java 8 Licence
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance
  sudo: yes

- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
  sudo: yes

